### ISSUE TITLE
Upgrade does not work Error 500

### ISSUE THREAD

**Issue by W4r10k** [DiogoParrinha/newpoints#13]
Upgrade does not work HTTP ERROR 500.

**Comment by W4r10k** [comment]
treated , only in /admin/modules/newpoints/upgrades.php line 112 
Remove continue;

**Comment by DiogoParrinha** [comment]
Thanks!

**Comment by DiogoParrinha** [comment]
Please note that this has been fixed in master a while ago, we just haven't released a 2.1.2 yet

**Comment by DiogoParrinha** [comment]
See https://github.com/DiogoParrinha/newpoints/commit/77e94d9e9a8f274b88f9ea856dd1008240d6c8e2
